[env:esp-wrover-kit]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
board_build.psram = enabled
build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DKEYPAD_MCP_ADDRESS=0x26

